---
title: "Visualização temporal de dados de COVID19."
author: "Elias T Krainski"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

count0 <- 0
l0 <- log(c(1, 3), 10)
ll <- vector('list', 5)
ll[[5]]$y <- c(rep(-8:-1, each=2)-rev(l0), -l0[2], 
               -0.15, 0, 0.15, l0[2],
               rep(1:8, each=2)+l0)
ll[[5]]$l <- paste0(c(rep(c(-300, -100, -30, -10, -3, -1), 3), 0, 
                    rep(c(1, 3, 10,30, 100,300), 3)), 
                    rep(c('M', 'K', '', 'K', 'M'), c(6, 6, 13, 6, 6)))
ll[[4]] <- lapply(ll[[5]], function(x) x[seq(2, length(x), 2)])
ll[[3]] <- lapply(ll[[5]], function(x) x[seq(1, length(x), 3)])
l0 <- log(c(1, 2, 5), 10)
ll[[2]] <- list(y=c(rep(-8:-1, each=3)-rev(l0), 
                -l0[3:2], -0.15, 0, 0.15, l0[2:3],
                rep(1:8, each=3)+l0))
ll0 <- c(1, 2, 5, 10, 20, 50, 100, 200, 500)
ll[[2]]$l <- paste0(c(rep(-rev(ll0), 3), 0, rep(ll0, 3)), 
                    rep(c('M', 'K', '', 'K', 'M'), 
                    c(9, 9, 19, 9, 9)))
library(mgcv)

if (file.exists('data/wdl.RData')) {
  load('data/wdl.RData') 
} else {
  brio <- FALSE
  source('rcode/wdata-update.R')
}
cn <- colnames(wdl[[1]])
Date <- as.Date(cn[7:length(cn)], 'X%Y%m%d')
lastday <- tail(Date, 1)

if (lastday<(Sys.Date()-1)) {
  brio <- FALSE
  source('rcode/wdata-update.R')
  cn <- colnames(wdl[[1]])
  Date <- as.Date(cn[7:length(cn)], 'X%Y%m%d')
  lastday <- tail(Date, 1)
}

wc.names <- levels(wdl[[1]]$Country.Region)
st.names <- setdiff(levels(wdl[[1]]$Province.State), 'total')
mu.names <- setdiff(levels(wdl[[1]]$City), 'total')
iisel <- which(wdl[[1]]$Province.State=='') 
nn.show <- sapply(wdl, function(m) 
  sum(m[iisel, ncol(m)], na.rm=TRUE))
lb.n <- list(1, 2); names(lb.n) <- 
  c(paste0('Casos (', nn.show[1], ')'), 
    paste0('Óbitos (', nn.show[2], ')')) 
    
```

```{r covid19time, echo=FALSE}
sidebarLayout(
  sidebarPanel(
    # checkboxInput(
    #   inputId = "cases", 
    #   label = paste0("Casos confirmados (total: ", 
    #                  sum(wdl[[1]][iisel, ncol(wdl[[1]])]), ')'),
    #   value = TRUE),
    # checkboxInput(
    #   inputId = "deaths", 
    #   label = paste0("Óbitos confirmados (total: ", 
    #                  sum(wdl[[2]][iisel, ncol(wdl[[1]])]), ')'),
    #   value = TRUE),
    radioButtons(
      inputId = "data", 
      label = "Confirmados (Total mundo)", 
      choices=lb.n, 
      selected = 1),
    selectInput(
      inputId = 'country', 
      label = 'País', 
      choices = wc.names, 
      selected = 'Brazil'),
    selectInput(
      inputId = 'state', 
      label = 'Estado/Província', 
      choices = st.names, 
      selected = 'PARANÁ'),
    selectInput(
      inputId = 'city', 
      label = 'Cidade', 
      choices = mu.names, 
      selected = 'Curitiba/PR'),
    dateRangeInput(
      inputId = 'dateRange',
      label = 'Data (intervalo):',
      start = as.Date('2020-01-20'), 
      end = Sys.Date() - 1, 
      format = "dd/mm/yy", 
      language = 'pt'),
    checkboxInput(
      inputId = "log10", 
      label = "Log 10", 
      value = TRUE),
    actionButton(
      inputId = "Exit", 
      label = "Exit")
),  
renderPlot({

 if (FALSE) ### just for test in .R 
   input <- list(data=1, country='Brazil', state='PARANÁ', city='Curitiba', log10=TRUE, dateRange=c('01/01/20', '01/09/20')) 

  #  kk <- reactive({
 #   validate(
  #    need(input$cases | input$deaths, 
   #        "Favor selecionar casos ou óbitos")
    #  )
    #c(input$cases+0, input$deaths+0)
  #})

  Date <- as.Date(cn[7:length(cn)], 'X%Y%m%d')
  k <- as.integer(input$data)
  iic <- wdl[[k]]$Country==input$country
  iis <- wdl[[k]]$Province.State==input$state
  if (sum(iic[iis])==0) iis <- iic
  iim <- wdl[[k]]$City==input$city
  if (sum(iic[iim])==0) iim <- iic
  iisel <- which((iic+iis+iim)==3)
  
  y <- unlist(wdl[[k]][iisel[1], 7:ncol(wdl[[k]])])
  iina <- (y==0) ##is.na(y)
  if (all(iina)) stop(safeError('Sem dados na seleção feita!'))
  iiy <- which(!iina)[1]:length(y)
  y <- y[iiy]
  Date <- Date[iiy]
  dy <- diff(c(0, y))
  r <- dy; r[which(dy<0)] <- 0
  i.r.na <- which(is.na(r))

  dtmp <- list(x=setdiff(1:length(r), i.r.na))
  dtmp$y <- r[dtmp$x]
  sss <- r

  if (length(dtmp$x)>9) {
    sssf <- gam(y ~ s(x), poisson(), data=dtmp)
    sss[dtmp$x] <- sssf$fitted
    pw <- pgamma(0:14, shape=(5/3)^2, scale=3^2/5)
    w <- diff(pw)/sum(diff(pw))
    n0 <- length(w)
    n1 <- length(dtmp$y)
    ee <- numeric(n0 + n1)
    if (FALSE) {
      ee[1:n0] <- (1-w)*sss[1:n0] * exp(-(1:n0))/exp(-1)
      for (i in 1:n1)
        ee[i+1:n0] <- ee[i+1:n0] + sss[i]*w
    } else {
      ee[1:n0] <- (1-w)*dtmp$y[1:n0] * exp(-(1:n0))/exp(-1)
      for (i in 1:n1)
         ee[i+1:n0] <- ee[i+1:n0] + dtmp$y[i] * w 
    }
    eesmall <- ee<0.1
    ee[eesmall] <- 0.1
##    ee[1:n1] <- ee[1:n1]*(sum(dtmp$y[1:n1])/sum(ee[1:n1]))
    dtmp$lE <- log(ee[1:n1])
    fRt <- gam(y~s(x), poisson(), data=dtmp, offset=lE)
    Rt <- exp(predict(fRt)); Rt[1:n0] <- NA
    aa <- 2 + sss; bb <- ee[1:n1]+2 
    rt.m <- aa/bb
    rt.a <- qgamma(0.025, aa, bb)
    rt.b <- qgamma(0.975, aa, bb)
    Rtlow <- qgamma(0.025, Rt*ee[1:n1], 1)/ee[1:n1]
    Rtupp <- qgamma(0.975, Rt*ee[1:n1], 1)/ee[1:n1]
  } else {
      sss[dtmp$x] <- 0.5*dtmp$y + 0.5*mean(dtmp$y)
  }
  ssslow <- sssupp <- sss
  ssslow[dtmp$x] <- qgamma(0.025, sss[dtmp$x], 1)
  sssupp[dtmp$x] <- qgamma(0.975, sss[dtmp$x], 1)

  xlm <- as.Date(input$dateRange, '%d/%m/%y')
  if (diff(xlm)<3) 
    stop(safeError('Selecione 3 ou mais dias!'))
  iip <- which((Date>=xlm[1]) & (Date<=xlm[2]))
  if (length(iip)<3) 
    stop(safeError('Selecione 3 ou mais dias!'))
  Date <- Date[iip]
  y <- y[iip]
  dy <- dy[iip]
  if (length(dtmp$x)>9) {
    Rt <- Rt[iip]
    Rtlow <- Rtlow[iip]
    Rtupp <- Rtupp[iip]
  }
  n.obs <- sum(dy, na.rm=TRUE) 
  sss <- sss[iip]
  ssslow <- ssslow[iip]
  sssupp <- sssupp[iip]
  ly <- log(y, 10)
  ldy <- dy  
  ldy[which(dy<0)] <- -log(abs(dy[which(dy<0)]), 10)
  ldy[which(dy==(-1))] <- -0.15
  ldy[which(dy==0)] <- 0
  ldy[which(dy>0)] <- log(dy[which(dy>0)], 10)
  ldy[which(dy==1)] <- 0.15
  if (input$log10) {
    y.plot <- ldy
    s.plot <- log(sss, 10)
    s.plot[which(sss<2)] <- sss[which(sss<2)]*0.15
    sl.plot <- log(ssslow, 10)
    sl.plot[which(ssslow<2)] <- ssslow[which(ssslow<2)]*0.15
    su.plot <- log(sssupp, 10)
    su.plot[which(sssupp<2)] <- sssupp[which(sssupp<2)]*0.15
  } else {
    y.plot <- dy
    s.plot <- sss
    sl.plot <- ssslow
    su.plot <- sssupp
  }

  ll[[1]] <- list(y=unique(sort(ldy))) 
  ll[[1]]$l <- 10^ll[[1]]$y
  if (length(ll[[1]]$y)>9) {
     ll[[1]]$l <- pretty(ll[[1]]$l)
     ll[[1]]$y <- log(ll[[1]]$l, 10)
  }
  ll[[1]]$l[ll[[1]]$y==(-0.15)] <- -1
  ll[[1]]$l[ll[[1]]$y==(0)] <- 0
  ll[[1]]$l[ll[[1]]$y==(0.15)] <- 1
  if (n.obs>count0) {
     par(mfrow=c(2,2), mar=c(2, 3, 0.1, 1), mgp=c(2, 0.5, 0))
  } else {
     par(mfrow=c(1,1), mar=c(2, 3, 1, 1), mgp=c(2, 0.5, 0))
  }
  xlm <- range(Date)
  rx <- as.numeric(diff(xlm))
  xlm[2] <- xlm[2] + rx*0.1 
  plot(Date, y.plot, pch=19, axes=FALSE, xlim=xlm,
       xlab='', ylab=c('Casos', 'Óbitos')[k])
##  polygon(c(Date, rev(Date), Date[1]), 
  ##        c(sl.plot, rev(su.plot), sl.plot[1]), 
    ##      col=gray(0.8, 0.5), border=gray(0.8, 0.5))
  if (n.obs>count0) {
    e.ic <- ee[n1+1]*c(tail(Rtlow, 1), tail(Rt,1), tail(Rtupp, 1))
    ##text(rep(xlm[2]-0.05*rx, 3), 
      ##   log(e.ic, 10), round(e.ic)) 
  }
  if (k==11) {
    oo <- unlist(wdl[[2]][iisel[1], 7:ncol(wdl[[2]])])
    oo[is.na(oo)] <- 0
    ood <- diff(cummax(c(0, oo)))
    points(as.Date(cn[7:length(cn)], 'X%Y%m%d'), 
           log(ood, 10),col=2, pch=8)
  }
  maxyplot <- max(y.plot, na.rm=TRUE)
  sssmin <- which.min(sss)[1]
  text(Date[sssmin], 
       maxyplot-(par()$usr[4]-maxyplot),  
       paste('Total:', n.obs), ##'(', sum(sss), ')'), 
       adj=sssmin/length(y.plot))
  axis(1, pretty(Date), format(pretty(Date), '%d %b'))
  nll <- findInterval(
      sum(findInterval(ll[[5]]$y, par()$usr[3:4])==1), 
      c(-0.5, 2.5, 9.5, 19.5, 29.5))
  if (input$log10) {
    axis(2, ll[[nll]]$y, ll[[nll]]$l, las=1)
  } else {
    axis(2, las=1)
  }
  lines(Date, s.plot, lwd=2)
  if (input$log10) {
    abline(h=ll[[nll]]$y, col=gray(0.5, 0.5), lty=3)
  } else {
    abline(h=pretty(par()$usr[3:4]), 
           col=gray(0.5, 0.5), lty=3)
  }
  
  if (n.obs>count0) { 
    plot(Date, c(NA, diff(sss)), xlim=xlm,
         ylim=range(diff(sss), 0, na.rm=TRUE), type='l', lwd=2, las=1, 
         xlab='', ylab='Velocidade de crescimento')  
    abline(h=0, col=gray(0.5, 0.5), lty=2)
    abline(h=pretty(par()$usr[3:4]), col=gray(0.5, 0.5), lty=3)
    plot(Date, 100*c(NA, diff(sss))/sss, 
         type='l', lwd=2, las=1, xlim=xlm,
         ylim=range(0, 100*c(NA, diff(sss))/sss, na.rm=TRUE),
         xlab='', ylab='Crescimento relativo (%)')  
    abline(h=0, col=gray(0.5, 0.5), lty=2)
    abline(h=pretty(par()$usr[3:4]), col=gray(0.5, 0.5), lty=3)
    plot(Date, Rt, axes=FALSE, type='l', xlim=xlm,
         ylim=range(c(1, Rtlow, Rtupp), na.rm=TRUE), lwd=2,
         xlab='', ylab='Número de reprodução efetivo')
    polygon(c(Date, rev(Date), Date[1]),
           c(Rtlow, rev(Rtupp), Rtlow[1]),
           col=gray(0.7, 0.7), border=gray(0.7, 0.7))
##    lines(Date, rt.m, col=2)
  ##  lines(Date, rt.a, col=rgb(1, 0.7, 0.7), lwd=2)
    ##lines(Date, rt.b, col=rgb(1, 0.7, 0.7), lwd=2)
    yyyl <- c(tail(Rtlow, 1), tail(Rt,1), tail(Rtupp, 1)) 
    yyll <- sprintf("%1.2f", yyyl)
    yr <- diff(par()$usr[3:4])
    ylr <- diff(range(yyyl))/2
    pry <- 0.95 + 0.05*ylr/yr
    yyyl[1] <- pmax(par()$usr[3]+0.02*yr, 
                    yyyl[2] - (pry*ylr + (1-pry)*yr))
    yyyl[3] <- pmin(par()$usr[4]-0.02*yr, 
                    yyyl[2] + (pry*ylr + (1-pry)*yr))
    text(rep(xlm[2]-0.05*rx, 3), yyyl, yyll) 
    axis(1, pretty(Date), format(pretty(Date), '%d %b'))
    axis(2, las=1)
    abline(h=1, col=gray(0.5, 0.5), lty=2)
    abline(h=pretty(par()$usr[3:4]), col=gray(0.5, 0.5), lty=3)
    if (FALSE) {
     nllx <- findInterval(
      sum(findInterval(ll[[5]]$y, par()$usr[1:2])==1),
      c(-0.5, 2.5, 9.5, 19.5, 29.5))
     if (nllx>1) {
      axis(1, ll[[nllx]]$y, ll[[nllx]]$l)
     } else {
      sx <- seq(par()$usr[1], par()$usr[2], length=5)
      l <- round(10^sx)
      axis(1, log(l, 10), l)
     }
    }
  }
  #observe({
   #     updateSelectInput(session, "city", choices = mu.names) 
  #})  
  
  observe({
    if(input$Exit > 0) {
      stopApp(NULL)
    }
  })
 
  }, 
 width = 500, height=500
 )
)
```
